version: "3"

networks:
  harbordmz:
    subnet: <Network in CIDR notation>
    gateway: <gateway-ip-address>

services:
  harbor:
    image: harbor/alpine:devel
    container_name: harbor
    hostname: harbor.example.local
    restart: "unless-stopped"
    networks: 
      harbordmz:
        ipv4_address: <IPv4-address>
    volumes:
    - ./config/:/config/:ro

